version: '3.8'

services:
  # MinIO for testing S3 requests
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9001:9000"
      - "9091:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # HAProxy Instance 1 - Active-Active Setup
  haproxy1:
    image: haproxy:3.0
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./extract_api_keys.lua:/usr/local/etc/haproxy/extract_api_keys.lua:ro
      - ./ssl/certs/haproxy.pem:/etc/ssl/certs/haproxy.pem:ro
      - ./config:/usr/local/etc/haproxy/config:ro
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8404/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HAProxy Instance 2 - Active-Active Setup
  haproxy2:
    image: haproxy:3.0
    ports:
      - "81:80"
      - "444:443"
      - "8405:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./extract_api_keys.lua:/usr/local/etc/haproxy/extract_api_keys.lua:ro
      - ./ssl/certs/haproxy.pem:/etc/ssl/certs/haproxy.pem:ro
      - ./config:/usr/local/etc/haproxy/config:ro
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8404/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
