version: '3.8'

services:
  # HAProxy Load Balancer with Rate Limiting
  haproxy1:
    image: haproxy:3.0-alpine
    container_name: haproxy1
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"  # Stats interface
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./api_key_extractor.lua:/etc/haproxy/api_key_extractor.lua:ro
      - ./api_key_groups.conf:/etc/haproxy/api_key_groups.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - haproxy1_socket:/var/run
    networks:
      - minio-network
    depends_on:
      - minio1
      - minio2
    restart: unless-stopped
    environment:
      - HAPROXY_INSTANCE=1

  # Second HAProxy instance for active-active setup
  haproxy2:
    image: haproxy:3.0-alpine
    container_name: haproxy2
    ports:
      - "81:80"
      - "444:443"
      - "8405:8404"  # Stats interface
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./api_key_extractor.lua:/etc/haproxy/api_key_extractor.lua:ro
      - ./api_key_groups.conf:/etc/haproxy/api_key_groups.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - haproxy2_socket:/var/run
    networks:
      - minio-network
    depends_on:
      - minio1
      - minio2
    restart: unless-stopped
    environment:
      - HAPROXY_INSTANCE=2

  # MinIO Server 1
  minio1:
    image: minio/minio:latest
    container_name: minio1
    ports:
      - "9001:9000"
      - "9011:9001"
    volumes:
      - minio1-data:/data
    networks:
      - minio-network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_SERVER_URL=http://minio1:9000
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Server 2  
  minio2:
    image: minio/minio:latest
    container_name: minio2
    ports:
      - "9002:9000"
      - "9012:9001"
    volumes:
      - minio2-data:/data
    networks:
      - minio-network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_SERVER_URL=http://minio2:9000
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Rate limit configuration updater service
  config-updater:
    image: alpine:latest
    container_name: config-updater
    volumes:
      - ./api_key_groups.conf:/etc/haproxy/api_key_groups.conf:rw
      - ./scripts:/scripts:ro
      - haproxy1_socket:/var/run/haproxy1
      - haproxy2_socket:/var/run/haproxy2
    networks:
      - minio-network
    command: >
      sh -c "
        apk add --no-cache inotify-tools socat curl &&
        /scripts/watch_config.sh
      "
    restart: unless-stopped

volumes:
  minio1-data:
  minio2-data:
  haproxy1_socket:
  haproxy2_socket:

networks:
  minio-network:
    driver: bridge