version: '3.8'

services:
  # MinIO for testing
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9000"
      - "9091:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # HAProxy with group-based rate limiting
  haproxy:
    image: haproxy:3.0
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./haproxy-groups.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - minio

  # Second HAProxy instance
  haproxy2:
    image: haproxy:3.0
    ports:
      - "81:80"
      - "8405:8404"
    volumes:
      - ./haproxy-groups.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - minio

volumes:
  minio_data: