version: '3.8'

services:
  # MinIO for testing
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9000"
      - "9091:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # HAProxy with advanced rate limiting
  haproxy:
    image: haproxy:3.0
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./haproxy-advanced.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./lua/api_key_extractor.lua:/etc/haproxy/lua/api_key_extractor.lua:ro
      - ./config/api_keys.json:/etc/haproxy/api_keys.json:ro
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8404/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Second HAProxy instance for active-active setup
  haproxy2:
    image: haproxy:3.0
    ports:
      - "81:80"
      - "8405:8404"
    volumes:
      - ./haproxy-advanced.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./lua/api_key_extractor.lua:/etc/haproxy/lua/api_key_extractor.lua:ro
      - ./config/api_keys.json:/etc/haproxy/api_keys.json:ro
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8404/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data: