version: '3.8'

services:
  # HyperDX All-in-One ClickStack
  hyperdx:
    image: docker.hyperdx.io/hyperdx/hyperdx-all-in-one:latest
    container_name: hyperdx
    ports:
      - "8080:8080"   # HyperDX Web UI
      - "4317:4317"   # OTEL gRPC
      - "4318:4318"   # OTEL HTTP
      - "8123:8123"   # ClickHouse HTTP
      - "9000:9000"   # ClickHouse Native
      - "27017:27017" # MongoDB
    environment:
      - HYPERDX_API_KEY=minio-rate-limiting-dev
      - NODE_ENV=development
      - USAGE_STATS_ENABLED=false
      - IS_LOCAL_APP_MODE=ALLOW_ANYONE
      - BETA_CH_OTEL_JSON_SCHEMA_ENABLED=true
      - HYPERDX_OTEL_EXPORTER_CLICKHOUSE_HOST=http://127.0.0.1:8123
      - CLICKHOUSE_HOST=http://127.0.0.1:8123
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=default
    volumes:
      - hyperdx_data:/app/data
      - hyperdx_clickhouse:/var/lib/clickhouse
      - hyperdx_mongodb:/data/db
      - ./minio_logs:/app/minio_logs:rw
      - ./proto:/app/packages/proto
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8123/ping || exit 1"]
      interval: 45s
      timeout: 30s
      retries: 10
      start_period: 120s

volumes:
  hyperdx_data:
  hyperdx_clickhouse:
  hyperdx_mongodb:

networks:
  default:
    name: hyperdx-clickstack