name: MinIO Rate Limit CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Install HAProxy for validation
        run: |
          sudo apt-get update
          sudo apt-get install -y haproxy lua5.3 luarocks

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run validation checks
        run: make ci-validate

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Run Go tests
        run: cd cmd/ratelimit-test && go test -v ./... -coverprofile=coverage.out

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: cmd/ratelimit-test/coverage.out

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 10
          docker-compose ps

      - name: Run quick tests
        run: make test-quick

      - name: Stop services
        run: docker-compose down

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cmd/ratelimit-test/results/

  build-docker:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test HAProxy Docker image
        run: |
          docker build -t minio-ratelimit-haproxy:test -f haproxy/Dockerfile ./haproxy
          docker run --rm minio-ratelimit-haproxy:test haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg

      - name: Build and test test-tool Docker image
        run: |
          docker build -t minio-ratelimit-test:test -f cmd/ratelimit-test/Dockerfile ./cmd/ratelimit-test
