# GitHub Actions Setup Script
# This script is used to prepare the GitHub Actions environment for testing

name: MinIO Rate Limit Setup

on:
  workflow_dispatch:

jobs:
  setup:
    name: Set Up GitHub Actions Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Check CI Environment
        run: |
          chmod +x ./scripts/ci_check_env.sh
          ./scripts/ci_check_env.sh

      - name: Install Go tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Generate test configurations
        run: |
          mkdir -p ./haproxy/config
          chmod +x ./scripts/generate_test_tokens.sh
          ./scripts/generate_test_tokens.sh -n 2

      - name: Prepare test environment
        run: |
          make ci-setup

      - name: Verify setup
        run: |
          echo "Verifying Go installation:"
          go version

          echo "Verifying HAProxy installation:"
          haproxy -v

          echo "Verifying Lua installation:"
          lua -v

          echo "Verifying golangci-lint installation:"
          golangci-lint --version

          echo "Verifying Docker Compose:"
          source docker-compose-command.sh
          echo "Docker Compose command: $DOCKER_COMPOSE_CMD"
          $DOCKER_COMPOSE_CMD version || true

          echo "Verifying test configuration files:"
          ls -la ./haproxy/config/

      - name: Prepare HAProxy for testing
        run: |
          # Create certificate directory
          mkdir -p ./haproxy/certs

          # Generate self-signed certificate for HAProxy
          openssl req -x509 -newkey rsa:2048 -nodes -keyout ./haproxy/certs/haproxy.pem \
            -out ./haproxy/certs/haproxy.pem -days 365 -subj "/CN=localhost"

      - name: Setup Docker Compose
        run: |
          # GitHub Actions runner has Docker Compose v2 installed as docker compose plugin
          docker compose version || echo "Using Docker Compose v1"

      - name: Run HAProxy validation explicitly
        run: |
          chmod +x ./scripts/haproxy_validate.sh

          # Prepare certificates directory for HAProxy
          mkdir -p ./haproxy/certs
          openssl req -x509 -newkey rsa:2048 -nodes -keyout ./haproxy/certs/haproxy.pem \
            -out ./haproxy/certs/haproxy.pem -days 1 -subj "/CN=localhost"

          # Run the validation with colors disabled
          CI=true CI_NO_COLOR=true ./scripts/haproxy_validate.sh

      - name: Run Lua validation explicitly
        run: |
          chmod +x ./scripts/lua_validate.sh

          # Run the validation using local lua since it's installed in the GitHub runner
          CI=true CI_NO_COLOR=true ./scripts/lua_validate.sh

      - name: Run full validation tests
        run: CI=true CI_NO_COLOR=true make validate-all
